name: Geneate epg.xml

on:
  push:

  schedule:
  - cron: '30 21 * * *'

jobs:

  generate:
    if: github.repository == 'git9527/tvsou-epg-generator'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests bs4 datetime
    - name: Generate epg.xml
      env:
        PAIRS: 061f902e:æ–°é—»ç»¼åˆ,120d425d:ç¤¾æ•™é¢‘é“,b0ceeb7e:ç”Ÿæ´»é¢‘é“,ded3cdcc:ä¸Šæµ·æ–°é—»ç»¼åˆ,6bb0f1cb:ä¸Šæµ·éƒ½å¸‚é¢‘é“,5da16c9b:ä¸Šæµ·æ•™è‚²å°
      run: |
         python main.py

    - name: Deploy ğŸš€
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: assets
        FOLDER: /tmp/epg-assets
        CLEAN: true
