name: Geneate epg.xml

on:
  push:
  schedule:
  - cron: '30 21 * * *'

jobs:

  generate:
    if: github.repository == 'git9527/tvsou-epg-generator'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests bs4 datetime
    - name: Generate epg.xml
      env:
        PAIRS: 061f902e:新闻综合,120d425d:社教频道,b0ceeb7e:生活频道,ded3cdcc:上海新闻综合,6bb0f1cb:上海都市频道,5da16c9b:上海教育台
      run: |
         python main.py
    - name: Setup aliyun oss
      uses: manyuanrong/setup-ossutil@master
      with:
        endpoint: oss-cn-shanghai.aliyuncs.com
        access-key-id: ${{ secrets.OSS_KEY_ID }}
        access-key-secret: ${{ secrets.OSS_KEY_SECRET }}
    - name: Copy file to aliyun
      run: ossutil cp -rf /tmp/epg.xml ${{ secrets.BUCKET }}
